//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> ID()
 * f1 -> <ASSIGN>
 * f2 -> Exp()
 * f3 -> <SEMICOLON>
 */
public class Assign implements Node {
   public ID f0;
   public NodeToken f1;
   public Exp f2;
   public NodeToken f3;

   public Assign(ID n0, NodeToken n1, Exp n2, NodeToken n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public Assign(ID n0, Exp n1) {
      f0 = n0;
      f1 = new NodeToken("=");
      f2 = n1;
      f3 = new NodeToken(";");
   }
   public Type accept(visitor.TypeVisitor v) {
    return v.visit(this);
 }
   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

