//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <AND>
 * f1 -> ExpFirst()
 */
public class ExpFirstAdjacent implements Node {
   public NodeToken f0;
   public ExpFirst f1;

   public ExpFirstAdjacent(NodeToken n0, ExpFirst n1) {
      f0 = n0;
      f1 = n1;
   }

   public ExpFirstAdjacent(ExpFirst n0) {
      f0 = new NodeToken("&&");
      f1 = n0;
   }
   public Type accept(visitor.TypeVisitor v) {
    return v.visit(this);
 }
   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

