//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> Factor()
 * f1 -> ( FactorAdjacent() )*
 */
public class Term implements Node {
   public Factor f0;
   public NodeListOptional f1;

   public Term(Factor n0, NodeListOptional n1) {
      f0 = n0;
      f1 = n1;
   }
   public Type accept(visitor.TypeVisitor v) {
    return v.visit(this);
 }
   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

