/* Generated By:JavaCC: Do not edit this line. AbhiLangConstants.java */
public interface AbhiLangConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int MULTI_LINE_COMMENT = 7;
  int LPAREN = 8;
  int RPAREN = 9;
  int LBRACE = 10;
  int RBRACE = 11;
  int LBRACKET = 12;
  int RBRACKET = 13;
  int SEMICOLON = 14;
  int COMMA = 15;
  int DOT = 16;
  int LT = 17;
  int NOT = 18;
  int AND = 19;
  int PLUS = 20;
  int MINUS = 21;
  int STAR = 22;
  int ASSIGN = 23;
  int BOOLEAN = 24;
  int CLASS = 25;
  int ELSE = 26;
  int EXTENDS = 27;
  int FALSE = 28;
  int IF = 29;
  int INT = 30;
  int LENGTH = 31;
  int NEW = 32;
  int MAIN = 33;
  int PUBLIC = 34;
  int PRINT = 35;
  int STATIC = 36;
  int STRING = 37;
  int THIS = 38;
  int TRUE = 39;
  int VOID = 40;
  int WHILE = 41;
  int RETURN = 42;
  int INTEGER_LITERAL = 43;
  int IDENTIFIER = 44;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"<\"",
    "\"!\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"=\"",
    "\"boolean\"",
    "\"class\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"if\"",
    "\"int\"",
    "\"length\"",
    "\"new\"",
    "\"main\"",
    "\"public\"",
    "\"System.out.println\"",
    "\"static\"",
    "\"String\"",
    "\"this\"",
    "\"true\"",
    "\"void\"",
    "\"while\"",
    "\"return\"",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
  };

}
