//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <DOT>
 * f1 -> <LENGTH>
 */
public class ArrayLength implements Node {
   public NodeToken f0;
   public NodeToken f1;

   public ArrayLength(NodeToken n0, NodeToken n1) {
      f0 = n0;
      f1 = n1;
   }

   public ArrayLength() {
      f0 = new NodeToken(".");
      f1 = new NodeToken("length");
   }
   public Type accept(visitor.TypeVisitor v) {
    return v.visit(this);
 }
   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

