//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "{"
 * f1 -> StatementList()
 * f2 -> "}"
 */
public class Block implements Node {
   public NodeToken f0;
   public StatementList f1;
   public NodeToken f2;

   public Block(NodeToken n0, StatementList n1, NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public Block(StatementList n0) {
      f0 = new NodeToken("{");
      f1 = n0;
      f2 = new NodeToken("}");
   }
   public Type accept(visitor.TypeVisitor v) {
    return v.visit(this);
 }
   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

