//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <CLASS>
 * f1 -> ID()
 * f2 -> <LBRACE>
 * f3 -> ( VarDecl() )*
 * f4 -> ( MethodDecl() )*
 * f5 -> <RBRACE>
 */
public class ClassDeclSimple implements Node {
   public NodeToken f0;
   public ID f1;
   public NodeToken f2;
   public NodeListOptional f3;
   public NodeListOptional f4;
   public NodeToken f5;

   public ClassDeclSimple(NodeToken n0, ID n1, NodeToken n2, NodeListOptional n3, NodeListOptional n4, NodeToken n5) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
   }

   public ClassDeclSimple(ID n0, NodeListOptional n1, NodeListOptional n2) {
      f0 = new NodeToken("class");
      f1 = n0;
      f2 = new NodeToken("{");
      f3 = n1;
      f4 = n2;
      f5 = new NodeToken("}");
   }
   public Type accept(visitor.TypeVisitor v) {
    return v.visit(this);
 }
   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

