//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> ExpFirst()
 * f1 -> ( ExpFirstAdjacent() )*
 */
public class Exp implements Node {
   public ExpFirst f0;
   public NodeListOptional f1;

   public Exp(ExpFirst n0, NodeListOptional n1) {
      f0 = n0;
      f1 = n1;
   }
   public Type accept(visitor.TypeVisitor v) {
    return v.visit(this);
 }
   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

