//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <COMMA>
 * f1 -> Type()
 * f2 -> ID()
 */
public class FormalRest implements Node {
   public NodeToken f0;
   public Type f1;
   public ID f2;

   public FormalRest(NodeToken n0, Type n1, ID n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public FormalRest(Type n0, ID n1) {
      f0 = new NodeToken(",");
      f1 = n0;
      f2 = n1;
   }
   public Type accept(visitor.TypeVisitor v) {
    return v.visit(this);
 }
   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

