//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <NEW>
 * f1 -> <INT>
 * f2 -> <LBRACKET>
 * f3 -> Exp()
 * f4 -> <RBRACKET>
 */
public class NewArray implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public NodeToken f2;
   public Exp f3;
   public NodeToken f4;

   public NewArray(NodeToken n0, NodeToken n1, NodeToken n2, Exp n3, NodeToken n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public NewArray(Exp n0) {
      f0 = new NodeToken("new");
      f1 = new NodeToken("int");
      f2 = new NodeToken("[");
      f3 = n0;
      f4 = new NodeToken("]");
   }
   public Type accept(visitor.TypeVisitor v) {
    return v.visit(this);
 }
   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

