//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <NEW>
 * f1 -> ID()
 * f2 -> <LPAREN>
 * f3 -> <RPAREN>
 */
public class NewObject implements Node {
   public NodeToken f0;
   public ID f1;
   public NodeToken f2;
   public NodeToken f3;

   public NewObject(NodeToken n0, ID n1, NodeToken n2, NodeToken n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public NewObject(ID n0) {
      f0 = new NodeToken("new");
      f1 = n0;
      f2 = new NodeToken("(");
      f3 = new NodeToken(")");
   }
   public Type accept(visitor.TypeVisitor v) {
    return v.visit(this);
 }
   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

