//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> ( <NOT> )+
 * f1 -> Elements()
 */
public class Not implements Node {
   public NodeList f0;
   public Elements f1;

   public Not(NodeList n0, Elements n1) {
      f0 = n0;
      f1 = n1;
   }
   public Type accept(visitor.TypeVisitor v) {
    return v.visit(this);
 }
   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

