//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> AddMinus()
 * f1 -> Term()
 */
public class TermAdjacent implements Node {
   public AddMinus f0;
   public Term f1;

   public TermAdjacent(AddMinus n0, Term n1) {
      f0 = n0;
      f1 = n1;
   }
   public Type accept(visitor.TypeVisitor v) {
    return v.visit(this);
 }
   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

