//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> Type()
 * f1 -> ID()
 * f2 -> <SEMICOLON>
 */
public class VarDecl implements Node {
   public Type f0;
   public ID f1;
   public NodeToken f2;

   public VarDecl(Type n0, ID n1, NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public VarDecl(Type n0, ID n1) {
      f0 = n0;
      f1 = n1;
      f2 = new NodeToken(";");
   }
   public Type accept(visitor.TypeVisitor v) {
    return v.visit(this);
 }
   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

